services:
  inspector-api-postgresql:
    container_name: inspector-api-postgresql
    image: postgres:17.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 2s
      retries: 20
    networks:
      - inspector-api-network
    volumes:
      - inspector_api_pg_data:/var/lib/postgresql/data

networks:
  inspector-api-network:
    driver: bridge

volumes:
  inspector_api_pg_data:
